// calculadora/src/main/Calculator.jsx
import React, { Component } from 'react';
import './Calculator.css';
import Button from '../components/Button';
import Display from '../components/Display';
const initialState = {
	displayValue: '0',
	clearDisplay:false,
	operation: null,
	values: [0,0],
	current: 0
}
export default class Calculator extends Component{
	state = {...initialState };

	clearMemory(){
		console.log('limpar');
		this.setState({...initialState});
	}
	
	setOperation(operation){
		console.log(operation);
		if(this.state.current === 0){
			this.setState({operation, current: 1, clearDisplay: true});
		}else{
			const equals = operation === '=';
			const currentOperation = this.state.operation;
			const values = [...this.state.values];
			switch(currentOperation){
				case '+':{values[0] += values[1];break;} 
				case '-':{values[0] -= values[1];break;}
				case '/':{values[0] /= values[1];break;}
				case '*':{values[0] *= values[1];break;}
				default:{values[0] = values[1];break;}				
			}
			values[1] = 0;
			console.log(values[0]);
			this.setState({displayValue: values[0], operation: equals ? null : operation,
			 current: equals ? 0 : 1, clearDisplay: !equals, values});		
		}
	}
	
	addDigit(n){
		console.log(n);
		if(n === '.' && this.state.displayValue.includes('.')){
			return
		}
		const clearDisplay = this.state.displayValue === '0' || this.state.clearDisplay;
		const currentValue = clearDisplay ? '' : this.state.displayValue;
		const displayValue = currentValue + n;
		this.setState({displayValue,clearDisplay: false});
		if(n !== '.'){
			const i = this.state.current;
			const newValue = parseFloat(displayValue);
			const values = [...this.state.values];
			values[i] = newValue;
			this.setState({values});
			console.log(values);
		}
	}
	
	render(){
	const addDigit = n => this.addDigit(n);
	const setOperation = op => this.setOperation(op);
	
		return(
			<div className="calculator">
				<Display value={this.state.displayValue} className="display" />
				<Button label="AC" click={() => this.clearMemory()} triple/>
				<Button label="/" click={setOperation} operation/>
				<Button label="7" click={addDigit}/>
				<Button label="8" click={addDigit}/>
				<Button label="9" click={addDigit}/>
				<Button label="*" click={setOperation} operation/>
				<Button label="4" click={addDigit}/>
				<Button label="5" click={addDigit}/>
				<Button label="6" click={addDigit}/>
				<Button label="-" click={setOperation} operation/>
				<Button label="1" click={addDigit}/>
				<Button label="2" click={addDigit}/>
				<Button label="3" click={addDigit}/>
				<Button label="+" click={setOperation} operation/>
				<Button label="0" click={addDigit} double/>
				<Button label="." click={addDigit}/>
				<Button label="=" click={setOperation}/>
			</div>
		);
	}
}

// calculadora-vue/src/main/Calculator.vue
<template>
<div class="calculator">
  <Display  :value="displayValue"/>
  <!-- O onCalcButtonClick eh um atributo customizavel criado no Button.vue-->
  <Button label="AC" triple @onCalcButtonClick="clearMemory"/>
  <Button label="/" operation @onCalcButtonClick="setOperation"/>
  <Button label="7" @onCalcButtonClick="addDigit"/>
  <Button label="8" @onCalcButtonClick="addDigit"/>
  <Button label="9" @onCalcButtonClick="addDigit"/>
  <Button label="*" operation @onCalcButtonClick="setOperation"/>
  <Button label="4" @onCalcButtonClick="addDigit"/>
  <Button label="5" @onCalcButtonClick="addDigit"/>
  <Button label="6" @onCalcButtonClick="addDigit"/>
  <Button label="-" operation @onCalcButtonClick="setOperation"/>
  <Button label="1" @onCalcButtonClick="addDigit"/>
  <Button label="2" @onCalcButtonClick="addDigit"/>
  <Button label="3" @onCalcButtonClick="addDigit"/>
  <Button label="+" operation @onCalcButtonClick="setOperation"/>
  <Button label="0" double @onCalcButtonClick="addDigit"/>
  <Button label="." @onCalcButtonClick="addDigit"/>
  <Button label="=" @onCalcButtonClick="setOperation"/>

</div>
</template>
<script>
import Display from '../components/Display';
import Button from '../components/Button';
export default{
  //Quando em componentes, o data retorna um objeto, no caso uma funcao que retorna um objeto.
  data:function(){
    return{ //Aqui temos os valores iniciais da aplicacao.
      displayValue:0,
      clearDisplay:false,
      operation:null,
      values:[0,0],
      current: 0
    }
  },
  components: {Button, Display},  
    methods: {
        clearMemory() {
          //Essa funcao retorna o objeto ao estado inicial do valor, ou seja limpa o objeto.
            Object.assign(this.$data, this.$options.data())
        },
        setOperation(operation) {
            if (this.current === 0) {
                this.operation = operation
                this.current = 1
                this.clearDisplay = true
            } else {
                const equals = operation === "="
                const currentOperation = this.operation
                try {
                    this.values[0] = eval(
                        `${this.values[0]} ${currentOperation} ${this.values[1]}`
                    )
                } catch (e) {
                    this.$emit('onError', e)
                }
                this.values[1] = 0
                this.displayValue = this.values[0]
                this.operation = equals ? null : operation
                this.current = equals ? 0 : 1
                this.clearDisplay = !equals
            }
        },
        addDigit(n) {
            if (n === "." && this.displayValue.includes(".")) {
                return
            }
            const clearDisplay = this.displayValue === "0"
                || this.clearDisplay
            const currentValue = clearDisplay ? "" : this.displayValue
            const displayValue = currentValue + n
            this.displayValue = displayValue
            this.clearDisplay = false       
            
            
            
             if (n !== ".") {
                 const i = this.current
                 const newValue = parseFloat(displayValue)
                 this.values[i] = newValue
             }
        }
    }


}
</script>
<style>
.calculator{
  height:320px;
  width:235px;
  border-radius:5px;
  overflow:hidden;
  display:grid;
  grid-template-columns: repeat(4,25%);
  grid-template-rows: 1fr 48px 48px 48px 48px 48px
}
</style>
